modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "techdinosauresandmagic"
version = "${version}"
displayName = "TechDinosauresAndMagic"
authors = ""
description = '''
A Mod whit tech dinosaures and magic 
'''
#logoFile = ""

[[dependencies.techdinosauresandmagic]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techdinosauresandmagic]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.techdinosauresandmagic]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "techdinosauresandmagic.mixins.json"
